export const keys = [
    { note: "C", keyboard: "q" },
    { note: "C#", keyboard: "2", isBlack: true },
    { note: "D", keyboard: "w" },
    { note: "D#", keyboard: "3", isBlack: true },
    { note: "E", keyboard: "e" },
    { note: "F", keyboard: "r" },
    { note: "F#", keyboard: "5", isBlack: true },
    { note: "G", keyboard: "t" },
    { note: "G#", keyboard: "6", isBlack: true },
    { note: "A", keyboard: "y" },
    { note: "A#", keyboard: "7", isBlack: true },
    { note: "B", keyboard: "u" },
    { note: "C", keyboard: "i" },
    { note: "C#", keyboard: "9", isBlack: true },
    { note: "D", keyboard: "o" },
    { note: "D#", keyboard: "0", isBlack: true },
    { note: "E", keyboard: "p" },
    { note: "F", keyboard: "z" },
    { note: "F#", keyboard: "s", isBlack: true },
    { note: "G", keyboard: "x" },
    { note: "G#", keyboard: "d", isBlack: true },
    { note: "A", keyboard: "c" },
    { note: "A#", keyboard: "f", isBlack: true },
    { note: "B", keyboard: "v" },
    { note: "C", keyboard: "b" },
    { note: "C#", keyboard: "h", isBlack: true },
    { note: "D", keyboard: "n" },
    { note: "D#", keyboard: "j", isBlack: true },
    { note: "E", keyboard: "m" },
    { note: "F", keyboard: "," },
    { note: "F#", keyboard: "l", isBlack: true },
    { note: "G", keyboard: ".", specialKey: "dot" },
    { note: "G#", keyboard: ";", isBlack: true },
    { note: "A", keyboard: "/", specialKey: "slash" },
    { note: "A#", keyboard: "'", isBlack: true },
    { note: "", keyboard: "" },
];
